{% set name = "spatialpandas" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 412bb93bb25f49b6c057e825560d14c06e71137228fa99dc007b3a191bfbabd1

build:
  number: 0
  skip: True  #[py<310 or s390x]
  # skipping s390x as it is not available for numba or pyarrow
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python
    - dask-core >=2025.1
    - fsspec >=2022.8
    - numba
    - pandas >=2.0
    - pyarrow >=14.0.1
    - retrying

test:
  imports:
    - spatialpandas
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/holoviz/spatialpandas
  description: |
    Spatialpandas provides Pandas and Dask extensions for vectorized
    spatial and geometric operations, such as fast, spatially indexed
    rendering of large collections of polygons, lines, or points.
  summary: Pandas extension arrays for spatial/geometric operations
  license: BSD-2-Clause
  license_file: LICENSE
  license_family: BSD
  dev_url: https://pypi.org/project/spatialpandas/
  doc_url: https://github.com/holoviz/spatialpandas/blob/main/README.md

extra:
  recipe-maintainers:
    - andrewannex
    - hoxbro
    - maximlt
    - philippjfr
