{% set name = "spatialpandas" %}
{% set version = "0.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ff2e348f90242ab7450b0b11549d1ac99638a933bc42580de6ed62cec4223128

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - param
  run:
    - dask-core
    - fsspec
    - numba
    - pandas
    - param
    - pyarrow >=1.0
    - python >=3.7
    - python-snappy
    - retrying

test:
  imports:
    - spatialpandas
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/holoviz/spatialpandas
  summary: Pandas extension arrays for spatial/geometric operations
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jonmmease
    - andrewannex
    - ianthomas23
    - maximlt
    - philippjfr
